Update schedule.yml

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -1,11 +1,38 @@
 name: Source trigger pauling
+run-name: Source trigger pauling from ${{ vars.SRC_REPOSITORY }}
 
 on:
   workflow_dispatch:
   # schedule:
   #   - cron: '*/5 * * * *'
 jobs:
+  check:
+    runs-on: ubuntu-latest
+    outputs:
+      changes: ${{ steps.add-and-commit.outputs.committed }}
+    steps:
+      - name: Get latest commit hash
+        env:
+          REPO: ${{ vars.SRC_REPOSITORY }}
+          BRANCH: main
+        run: |
+          COMMIT_HASH=$(curl -s "https://api.github.com/repos/$REPO/commits/$BRANCH" | jq -r '.sha')
+          if [ -z "$COMMIT_HASH" ]; then
+            echo "Failed to retrieve commit hash or the result is empty."
+            exit 1
+          fi
+          SECURE_HASH=$(echo -n "$COMMIT_HASH" | sha256sum | awk '{print $1}')
+          echo "$SECURE_HASH" > ./current_hash.txt
+      - name: Add and commit if changed
+        uses: EndBug/add-and-commit@v9
+        with:
+          add: 'current_hash.txt'
+          message: 'Update current_hash.txt'
+          author_name: "github-actions[bot]"
+          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
   remote-dispatch:
+    needs: check
+    if: ${{ needs.check.outputs.changes == 'true' }}
     runs-on: ubuntu-latest
     steps:
       - id: generate_token
@@ -18,15 +45,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           path: main
-      - name: Get latest commit hash
-        env:
-          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-          REPO: ${{ vars.SRC_REPOSITORY }}
-          BRANCH: main
-        run: |
-          COMMIT_HASH=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-            "https://api.github.com/repos/$REPO/commits/$BRANCH" | jq -r '.sha')
-          echo "Commit Hash: $COMMIT_HASH"
       # - name: Repository Dispatch
       #   uses: peter-evans/repository-dispatch@v3
       #   with:
